### ISSUE TITLE
Table of Content is blank page

### ISSUE THREAD

**Issue by hungdn2703** [HakanL/WkHtmlToPdf-DotNet#22]
Hi,
I'm implementing functionality to export pdf file used ASP.Net core 2.2
In the first time run project, i can export pdf with table of content as well. But in the next time, it's blank page.
```
[WkHtml("isTableOfContent")]
public bool IsTableOfContents { get; set; }
```
Can you help check it?

**Comment by HakanL** [comment]
Does it work with other types of pages?

**Comment by hungdn2703** [comment]
Each of pages is worked as well, but table of content is exceptioned.
I ran my code on console app, it's good. But with ASP.NET (RESTful API), the issue is happened.
My config code for pdf configuration:
```
public static void ConfigPdfLibrary(this IServiceCollection services)
{
    string fileName = GetPdfLibraryFileName();
    CustomAssemblyLoadContext context = new CustomAssemblyLoadContext();
    context.LoadUnmanagedLibrary(fileName);

    ITools pdfTools = new PdfTools();
    IConverter synchronizedConverter = new SynchronizedConverter(pdfTools);
    services.AddSingleton<IConverter>(synchronizedConverter);
}
```

**Comment by HakanL** [comment]
If I check the fixes in 0.12.6 I can see that TOC is listed, perhaps 0.12.5 isn't properly working with TOC? It's always best to test your HTML with the native wkhtmltopdf command line tool to see if the issue is with wkhtmltopdf, or with this wrapper. That being said, I've tested to upgrade to 0.12.6, but I haven't had a chance to test it, feel free to try it out if you can, it's in this branch: `test-0.12.6`. You'll find the NuGet package here: https://www.nuget.org/packages/Haukcode.WkHtmlToPdfDotNet/1.3.0-test-0.12.6
I'm not sure why you load the managed library directly in your code, have you looked at the WebServer sample in this repo?

**Comment by hungdn2703** [comment]
Thank you for your updated.
I've updated my code and upgraded to new version. But the issue is still not resolved.
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(typeof(IConverter), new SynchronizedConverter(new PdfTools()));

    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```
ConvertController.cs
```
[HttpGet]
public IActionResult Get()
{
    var tableOfContents = new TableOfContentsSettings() { };

    var doc = new HtmlToPdfDocument()
    {
        GlobalSettings = {
            PaperSize = PaperKind.A4,
            Orientation = Orientation.Landscape,
        },

        Objects = {
            tableOfContents,
                new ObjectSettings()
            {
                Page = "template.html",

            }
        }
    };

    byte[] pdf = _converter.Convert(doc);

    return new FileContentResult(pdf, "application/pdf");
}
```
1. First time:
![first_time](https://user-images.githubusercontent.com/19406619/95164789-dd2b5d80-07d4-11eb-8502-f12068d40075.PNG)
2. Next time
![next_time](https://user-images.githubusercontent.com/19406619/95164777-d43a8c00-07d4-11eb-849b-7ec0b9ff0f97.PNG)
[first_time.pdf](https://github.com/HakanL/WkHtmlToPdf-DotNet/files/5331687/first_time.pdf)
[next_time.pdf](https://github.com/HakanL/WkHtmlToPdf-DotNet/files/5331689/next_time.pdf)

**Comment by HakanL** [comment]
Hmm, thanks for the details. Unfortunately I don't know much about wkhtmltopdf itself, I just forked an existing wrapper and updated it and made it so it includes all binaries. I'm not sure I'm able to figure out a solution for this, we may need to depend on the community to see if someone can figure out what's going on. Maybe you can add a test method to the samples in this repo in a PR so it's easy for someone to test the scenario?

**Comment by hungdn2703** [comment]
Hi HakaL,
Thank you for your updated. I've create unit test project and write convert to pdf test method. It's included table of contents settings at: [https://github.com/HakanL/WkHtmlToPdf-DotNet/pull/23](url)
Test method:
```
[TestMethod]
public void ConvertToPdfTest()
{
    for (int i = 1; i < 3; i++)
    {
        var pdf = GetPdf();
        File.WriteAllBytes($"Test {i}.pdf", pdf);

        Assert.IsNotNull(pdf);
    }
}
```

**Comment by HakanL** [comment]
I merged in the PR and also did some refactoring in the code. The issue is that the unit test runs fine here. Can you test with the latest code in `master` to confirm if it works for you as well?

**Comment by hungdn2703** [comment]
Thank HakanL, I can run your refactor code as well. But the issue with table of contents is not resolved.
I'm investigating it and try to find out the solution.
```
[TestMethod]
public void RepeatTableOfContents()
{
    for (int i = 0; i < 2; i++)
    {
        byte[] pdf = GetPdfWithTableOfContents();

        Assert.IsNotNull(pdf);
        Assert.IsTrue(pdf.Length > 10000);

        WriteToPdfFile(pdf);
    }
}

private void WriteToPdfFile(byte[] pdf, string fileName = "")
{
    if (!Directory.Exists("Files"))
    {
        Directory.CreateDirectory("Files");
    }
    if (string.IsNullOrEmpty(fileName))
    {
        fileName = $"{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";
    }
    using (var stream = new FileStream(Path.Combine("Files", fileName), FileMode.Create))
    {
        stream.Write(pdf, 0, pdf.Length);
    }
}
```
The table of contents page in file 2 still is blank
File1: [20201008023350.pdf](https://github.com/HakanL/WkHtmlToPdf-DotNet/files/5345041/20201008023350.pdf)
File2: [20201008023351.pdf](https://github.com/HakanL/WkHtmlToPdf-DotNet/files/5345039/20201008023351.pdf)

**Comment by HakanL** [comment]
Hmm, odd, is the unit test failing if you run it in Windows (I’ve only tested it in VS on Windows)? Is the length set to over > 10k but the file is corrupt?

**Comment by hungdn2703** [comment]
I'm using VS on Windows too. The unit test is not failed but the pdf file was not corrected.

**Comment by HakanL** [comment]
I attempted a refactoring of the converter to see if it would make a difference, but it doesn't. So if I run all unit tests then it's successful, but if I run just the repeat unit test then it fails. I tried to add a sleep just to see if something weird was going on, but it didn't help. I'm not sure what's going on here, very odd.

**Comment by hungdn2703** [comment]
I've checked the code and find out the root-cause. You can see the result in below capture
Green is result for all unit test in ConvertTest class
Red is result when i run RepeatTableOfContents test method only
![image](https://user-images.githubusercontent.com/19406619/95540122-4ea81d80-0a1a-11eb-8a2e-70aa90feaef9.png)
When you run all of unit tests, the ConvertToPdf test method will be run in the first time. After that, it can't generate TOC in the next time (file size 13kb).
If we just run RepeatTableOfContents method only, it can generate TOC in the first time. The pdf file size is 23KB, after that it can't generate TOC again => the file size will be 13KB

**Comment by HakanL** [comment]
Ah, good catch. I've changed the unit test to check the first generated file as well. Obviously that doesn't solve the actual problem, but at least we have a way to confirm.

**Comment by MKMatthew** [comment]
In my recent project, I'm dealing with the identical problem. Has anyone managed to resolve this case?
